### ISSUE TITLE
Manual Configuration AKV10022: Invalid audience error

### ISSUE THREAD

**Issue by dhei** [Azure/kubernetes-kms#98]
**Describe the issue**

(Though I opened this issue as a bug, but I am not sure if it's a bug or a setup issue on my side.)

I followed [manual configurations](https://github.com/Azure/kubernetes-kms/blob/master/docs/manual-install.md) and ran into an issue with [Deploy the KMS plugin](https://github.com/Azure/kubernetes-kms/blob/master/docs/manual-install.md#3-deploy-the-kms-plugin) step.

The azure-kms-provider pod we used is the same as the one from the **Deploy the KMS plugin** step.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: azure-kms-provider
  namespace: kube-system
  labels:
    component: azure-kms-provider
spec:
  priorityClassName: system-node-critical
  hostNetwork: true
  containers:
    - name: azure-kms-provider
      image: mcr.microsoft.com/oss/azure/kms/keyvault:v0.0.11
      imagePullPolicy: IfNotPresent
      args:
        - --listen-addr=unix:///opt/azurekms.socket             # [OPTIONAL] gRPC listen address. Default is unix:///opt/azurekms.socket
        - --keyvault-name=${KV_Name}                 # [REQUIRED] Name of the keyvault
        - --key-name=${KEY_NAME}                             # [REQUIRED] Name of the keyvault key used for encrypt/decrypt
        - --key-version=${KEY_VERSION}        # [REQUIRED] Version of the key to use
        - --log-format-json=false                               # [OPTIONAL] Set log formatter to json. Default is false.
        - --healthz-port=8787                                   # [OPTIONAL] port for health check. Default is 8787
        - --healthz-path=/healthz                               # [OPTIONAL] path for health check. Default is /healthz
        - --healthz-timeout=20s                                 # [OPTIONAL] RPC timeout for health check. Default is 20s
        - -v=1
      ports:
        - containerPort: 8787                                   # Must match the value defined in --healthz-port
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /healthz                                        # Must match the value defined in --healthz-path
          port: 8787                                            # Must match the value defined in --healthz-port
        failureThreshold: 2
        periodSeconds: 10
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 4
          memory: 2Gi
      volumeMounts:
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
        - name: etc-ssl
          mountPath: /etc/ssl
          readOnly: true
        - name: sock
          mountPath: /opt
  volumes:
    - name: etc-kubernetes
      hostPath:
        path: /etc/kubernetes
    - name: etc-ssl
      hostPath:
        path: /etc/ssl
    - name: sock
      hostPath:
        path: /opt
```

We get `AKV10022: Invalid audience. Expected https://vault.azure.net, found: https://management.core.windows.net/` error when deploying the pod. 

```
I0525 16:38:05.933121       1 main.go:86] Listening for connections on address: /opt/azurekms.socket
E0525 16:38:14.979721       1 server.go:50] "failed to encrypt" err="failed to encrypt, error: keyvault.BaseClient#Encrypt: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code=\"Unauthorized\" Message=\"AKV10022: Invalid audience. Expected https://vault.azure.net, found: https://management.core.windows.net/.\""
E0525 16:38:25.081137       1 server.go:50] "failed to encrypt" err="failed to encrypt, error: keyvault.BaseClient#Encrypt: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code=\"Unauthorized\" Message=\"AKV10022: Invalid audience. Expected https://vault.azure.net, found: https://management.core.windows.net/.\""
I0525 16:38:25.096147       1 main.go:120] received shutdown signal
I0525 16:38:25.096184       1 main.go:102] terminating the server
```
I am not sure where did the `https://management.core.windows.net` audience come from as we don't use that audience in our project. I searched this codebase for `https://management.core.windows.net` but couldn't find it used anywhere either. Any help is appreciated.

**KMS Plugin for Key Vault version**

v0.0.11

**Kubernetes version**

v1.19.7
